//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public int cust_id { get; set; }
        public string sir_name { get; set; }
        public string name { get; set; }
        public bool payed { get; set; }
        public string address { get; set; }
        public string phone1 { get; set; }
        public string phone2 { get; set; }
        public string mobile { get; set; }
        public string synoik { get; set; }
        public string tk { get; set; }
        public string poli { get; set; }
        public string notes { get; set; }
        public string code { get; set; }
        public string Field1 { get; set; }
        public string Field2 { get; set; }
        public string Field3 { get; set; }
        public string Field4 { get; set; }
        public string Field5 { get; set; }
        public bool edit { get; set; }
        public string user { get; set; }
        public string contractor_name { get; set; }
        public Nullable<short> discount_id { get; set; }
        public Nullable<short> doy_id { get; set; }
        public Nullable<short> poli_id { get; set; }
        public string country { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public Nullable<int> fpa_zone_id { get; set; }
        public Nullable<short> ship_type_id { get; set; }
        public Nullable<short> paym_type_id { get; set; }
        public string photos { get; set; }
        public string offers { get; set; }
    }
}
